In [9]:
# Download a CSV file of IPL match results 
# from Kaggle or any open dataset, then use pandas read_csv()
#  to load it into a DataFrame and display the first 10 rows using head().

import pandas as pd

ipl = pd.read_excel(r"C:\Users\Admin\OneDrive\Documents\ipl_matches.xlsx")

ipl.head(10)

  Match     Team1      Team2      Winner
0     1         MI         CSK        MI
1    2         RCB        KKR        KKR
2    3         CSK        RCB        CSK

In [22]:
import pandas as pd

mobile_expenses = pd.read_excel(
    r"C:\Users\Admin\OneDrive\Documents\mobile_expenses.xlsx"
)

mobile_expenses.tail(3)

            Unnamed: 0     Unnamed: 1 Unnamed: 2
3  2026-05-10 00:00:00   Mobile cover        150
4  2026-07-10 00:00:00      Data pack        100
5  2026-10-10 00:00:00  Charger cable        200

In [29]:
import pandas as pd

food = pd.read_excel(r"C:\Users\Admin\OneDrive\Documents\zometo.xlsx")

food.info()
food.describe()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Restaurant        8 non-null      str
 1   City              8 non-null      str
 2   Cuisine           8 non-null      str
 3   Rating            8 non-null      float64
 4   Average Cost (₹)  8 non-null      int64
 5   Online Delivery   8 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 516.0 bytes

         Rating  Average Cost (₹)
count  8.000000          8.000000
mean   4.150000        387.500000
std    0.244949        140.788595
min    3.800000        200.000000
25%    3.975000        287.500000
50%    4.150000        375.000000
75%    4.325000        475.000000
max    4.500000        600.000000

In [32]:
filtered_data = food.head(20)

filtered_data.to_csv("filtered_data.csv", index=False)

In [33]:
food.to_excel("food_analysis.xlsx", sheet_name="Analysis2024", index=False)